# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  mode: classic
  theme_day: custom
  theme_night: custom
  font: custom
  font_size: M
  # color: blue

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Hi, I’m Arash Rocky! 👋 I’m currently pursuing my research in computer vision at University of Windsor (UoW) under the supervision of Prof. Jonathan Wu).' # TODO
    twitter: ''
  analytics:
    enable: false  # Add this line
    google_analytics: ''
    googleAnalytics: ''  # Add this line
    baidu_tongji: ''
    google_tag_manager: ''
    microsoft_clarity: ''
  verification:
    google: 'I8B3FMVsTRq00dane3Sx_p0xsOXbjD-8SpK5N87-gso'
    baidu: ''
# <meta name="google-site-verification" content="I8B3FMVsTRq00dane3Sx_p0xsOXbjD-8SpK5N87-gso" />

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: '© 2025-{year} Arash Rocky. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features
features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/<username>/<repository>'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    # shape: circle
    shape: square
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 15

# Markdown TOC
markup:
  tableOfContents:
    endLevel: 4
    ordered: false
    startLevel: 2

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true